version: '3.8'

services:
  web-blue:
    build: ./blue
    container_name: web-blue

  web-green:
    build: ./green
    container_name: web-green

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web-blue
      - web-green
